language: ruby
rvm:
  - 2.1
  - 2.0
  - 1.9.3
gemfile:
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_3.2.gemfile
